"use client";
import StoreProvider from "@/app/redux/provider";
import NiceModal from "@ebay/nice-modal-react";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <StoreProvider>
          <div lang="en">
            <div>{children}</div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
