// import Provider from "@/app/conponents/Provide"

import Provider from "@/app/conponents/Provide";
import StoreProvider from "@/app/redux/provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div lang="en">
          <StoreProvider>
            <Provider>
              <div>{children}</div>
            </Provider>
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
